### ISSUE TITLE
2.1.0 is a breaking change for node 0.12.x

### ISSUE THREAD

**Issue by Maximization** [ghaiklor/passport-instagram-token#31]
After updating to 2.1.0 I get the following error:

```
class InstagramTokenStrategy extends _passportOauth.OAuth2Strategy {
^^^^^
SyntaxError: Unexpected reserved word
```

It seems that 2.1.0 doesn't support node versions 0.12.x or earlier. Specifically in this commit when upgrading to Babel 6: https://github.com/ghaiklor/passport-instagram-token/commit/36f6ae06a83127dcbd336cb6095346562d395ae3 the preset `babel-preset-es2015-node4` is used which adds missing features between ES6 and Node 4. Is it possible to use `babel-preset-es2015`instead so all ES6 features are compiled and older versions of node will remain supported?

**Comment by ghaiklor** [comment]
@Maximization yes, it's built with Babel only for Node 4.x or higher.

**Comment by Maximization** [comment]
@ghaiklor I've submitted a PR for this. Let me know if you're willing to merge and maintain support for 0.12. Otherwise perhaps it's better to bump the major version.

**Comment by ghaiklor** [comment]
@Maximization published under new minor version. Node 10.x doesn't support scoped packages, so Travis CI can't test if that works but it should.
