### ISSUE TITLE
export default behaviour changed since Babel 6

### ISSUE THREAD

**Issue by Maximization** [ghaiklor/passport-instagram-token#33]
Babel 6 has changed the behaviour of `export default` to adhere to ES6 specs. From now on the default export is exported as a prop on the module.exports object. This means that the library has to be required as follows `require('passport-instagram-token).default`.

More on this https://phabricator.babeljs.io/T2212. I've also found this in-depth article informative https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0#.yr32uasbs

A backwards compatible solution would be to add a Babel plugin that deals with this: https://github.com/59naga/babel-plugin-add-module-exports. I see you did the same in passport-facebook-token library a while ago https://github.com/drudge/passport-facebook-token/commit/59bbfb3499b06d8059e4a5070892572ed834712a. I'll go ahead and add a PR for this if you don't mind.

**Comment by ghaiklor** [comment]
@Maximization Babel 6 is disappointing me :worried:

**Comment by ghaiklor** [comment]
@Maximization published.

**Comment by Maximization** [comment]
@ghaiklor Works like a charm again, thanks! Yeah, Babel hasn't been particularly clear about this change 😉
