### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by ilyanoskov** [ghaiklor/passport-instagram-token#97]
Hello, I am a beginner programmer and I was trying to figure out this passport auth strategy. 

I am trying to write a little client application that would just return a full name of a user that authenticated through this strategy. How would I do this? 

```
var express = require ('express');
var InstagramTokenStrategy = require('passport-instagram-token');
var passport = require('passport');
var app = express();

passport.use(new InstagramTokenStrategy({
        clientID: '243asdba35daa618s644db84d99e2d1ccb7be0',
        clientSecret: '3dd3f81f20asda8743asd169asde7e1ff04f46c6c8',
        passReqToCallback: true

}, function(req, accessToken, refreshToken, profile, next) {
    User.findOrCreate({'instagram.id': profile.id}, function(error, user) {
                return next(error, user);

    });

}));
```

**Comment by ghaiklor** [comment]
@ilyanoskov what's the problem you faced ?

**Comment by ilyanoskov** [comment]
@ghaiklor the problem is that I don't think this code authenticates my instagram app at all

**Comment by ghaiklor** [comment]
@ilyanoskov you didn't provide errors, logs, anything that can be useful here. Instead, you just saying that code doesn't work. I can't help you until you provide more information.

**Comment by ilyanoskov** [comment]
```
var passport = require ('passport');
var InstagramTokenStrategy = require ('passport-instagram-token');
var express = require ('express');
var app = express();

passport.use (new InstagramTokenStrategy ({
    clientID : 'aaaaaaaaaaaaa' ,
    clientSecret: 'bbbbbbbbbbbbbbb',
    passReqToCallback : true
}, function (req, accessToken, refreshToken, profile, next) {
console.log(accessToken);
    User.findOrCreate({'instagram.id' : profile.id}, function (error, user) {
        return next (error, user);
    });
}));

app.get('/auth/instagram', passport.authenticate('instagram-token'));
```

how do I get an access token out of this code? Is there something I am missing?

 I am new to this, and I am trying to write a simple instagram app that would analyze my own data. All I need is an access token so I can use it with other libraries. I tried using this code from README but it does not do much?

**Comment by ghaiklor** [comment]
@ilyanoskov this library is not returning to you access token. Vice versa, you need to provide access token to this library for parsing your profile. How to get access token you can find out on official Instagram Developer Guides.

**Comment by ilyanoskov** [comment]
@ghaiklor Thank you very much, that's the answer I was looking for!
